# Generated by Django 3.0.5 on 2020-05-22 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shirdo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='do',
            old_name='competed',
            new_name='completed',
        ),
    ]
